#!/usr/bin/env php
<?php

$autoloadPath1 = __DIR__ . '/../../autoload.php';
$autoloadPath2 = __DIR__ . '/vendor/autoload.php';

if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h|--help)
  gendiff (-v|--version)
  gendiff [--format <fmt>] <firstFile> <secondFile>

Options:
  -h --help                     Show this screen
  -v --version                  Show version
  --format <fmt>                Report format [default: stylish]

DOC;

$args = Docopt::handle($doc, array('version' => '1.0.0'));

try {
    $firstFile = $args['<firstFile>'];
    $secondFile = $args['<secondFile>'];
    
    // Парсим файлы
    $data1 = \Differ\Parsers\parseFile($firstFile);
    $data2 = \Differ\Parsers\parseFile($secondFile);
    
    // Выводим содержимое файлов
    echo "First file content:\n";
    print_r($data1);
    echo "\n";
    
    echo "Second file content:\n";
    print_r($data2);
    echo "\n";
    
} catch (\Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}
